# -*- coding: utf-8 -*-
"""Generative_AI_driven_adaptive_decision_making_ (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7tWi2H6ox7PDtcAj4n95OK-PbGgnpTA

# **Datalink**

"https://www.kaggle.com/datasets/ziya07/intelligent-manufacturing-dataset"

# **Import Libaries**
"""

import warnings
warnings.filterwarnings("ignore")

import os
import re
import glob
import scipy
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path
from pprint import pprint
from IPython.display import clear_output
from collections import defaultdict, OrderedDict
from tqdm.notebook import tqdm_notebook as tqdm_nb

from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.multiclass import OneVsRestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (ConfusionMatrixDisplay, classification_report, accuracy_score, roc_auc_score, precision_recall_fscore_support, log_loss, confusion_matrix)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from torch.optim.lr_scheduler import CosineAnnealingLR, SequentialLR, LinearLR

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print('[device]', device)

"""# **Load Dataset**"""

import pandas as pd

file_path = "/content/manufacturing_6G_dataset.csv"
df = pd.read_csv(file_path)


df_info = df.info()
df_head = df.head()

df_info, df_head

"""# **Data Preprocessing**"""

from sklearn.preprocessing import LabelEncoder, StandardScaler
import numpy as np

# Convert 'Timestamp' to datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

# Encode categorical columns
label_encoders = {}
for col in ['Operation_Mode', 'Efficiency_Status']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Store original feature names before scaling
original_features = df.columns.difference(['Timestamp'])

# Normalize numerical features
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[original_features] = scaler.fit_transform(df[original_features])

df_scaled.head()

"""# **Anomaly Detection Module (Autonomous)**"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


# Feature selection
features = ['Temperature_C', 'Vibration_Hz', 'Power_Consumption_kW',
            'Network_Latency_ms', 'Packet_Loss_%', 'Error_Rate_%']
scaler = StandardScaler()
X = scaler.fit_transform(df[features])
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

# Autoencoder (Keras)
import numpy as np
from tensorflow.keras import layers, models

input_dim = X_train.shape[1]
autoencoder = models.Sequential([
    layers.Input(shape=(input_dim,)),
    layers.Dense(4, activation='relu'),
    layers.Dense(2, activation='relu'),
    layers.Dense(4, activation='relu'),
    layers.Dense(input_dim)
])

autoencoder.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train model
history = autoencoder.fit(
    X_train, X_train,
    epochs=50,
    batch_size=128,
    validation_split=0.1,
    verbose=1
)

# Plot Keras training history
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title("MSE Loss (Autoencoder)")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history['mae'], label='Train MAE')
plt.plot(history.history['val_mae'], label='Val MAE')
plt.title("MAE (Autoencoder)")
plt.xlabel("Epoch")
plt.ylabel("Mean Absolute Error")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Variational Autoencoder (VAE)
import torch
import torch.nn as nn
import torch.optim as optim

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

class VAE(nn.Module):
    def __init__(self, input_dim, latent_dim=2):
        super(VAE, self).__init__()
        self.fc1 = nn.Linear(input_dim, 8)
        self.fc_mu = nn.Linear(8, latent_dim)
        self.fc_logvar = nn.Linear(8, latent_dim)
        self.fc2 = nn.Linear(latent_dim, 8)
        self.fc3 = nn.Linear(8, input_dim)

    def encode(self, x):
        h1 = torch.relu(self.fc1(x))
        return self.fc_mu(h1), self.fc_logvar(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h2 = torch.relu(self.fc2(z))
        return self.fc3(h2)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

def vae_loss(recon_x, x, mu, logvar):
    recon_loss = nn.MSELoss()(recon_x, x)
    kld = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kld

vae = VAE(input_dim=X_train.shape[1])
optimizer = optim.Adam(vae.parameters(), lr=0.001)

vae_losses = []
for epoch in range(50):
    vae.train()
    optimizer.zero_grad()
    recon, mu, logvar = vae(X_train_tensor)
    loss = vae_loss(recon, X_train_tensor, mu, logvar)
    loss.backward()
    optimizer.step()
    vae_losses.append(loss.item())
    if epoch % 5 == 0:
        print(f"[VAE] Epoch {epoch} Loss: {loss.item():.4f}")

# VAE Anomaly Detection
vae.eval()
with torch.no_grad():
    recon_test, _, _ = vae(X_test_tensor)
    recon_error = torch.mean((X_test_tensor - recon_test) ** 2, dim=1).numpy()

threshold = np.percentile(recon_error, 95)
anomalies = recon_error > threshold
print(f"Detected {np.sum(anomalies)} anomalies out of {len(recon_error)} samples.")

# Plot VAE reconstruction error
plt.figure(figsize=(10, 4))
plt.hist(recon_error, bins=50, alpha=0.7, label='Reconstruction Error')
plt.axvline(threshold, color='red', linestyle='--', label=f"Threshold = {threshold:.4f}")
plt.title("VAE Reconstruction Error Distribution")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Isolation Forest for Anomaly Detection

print("\n Running Isolation Forest Anomaly Detection...")
iso_model = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
iso_model.fit(X_train)

# Predict anomalies (-1 means anomaly)
anomalies = iso_model.predict(X_test) == -1
n_anomalies = np.sum(anomalies)
print(f"Detected {n_anomalies} anomalies out of {len(X_test)} samples.")

# Visualize anomaly scores
scores = iso_model.decision_function(X_test)
plt.figure(figsize=(10, 4))
plt.hist(scores, bins=50, alpha=0.7, label='Anomaly Score')
plt.axvline(np.percentile(scores, 5), color='red', linestyle='--', label='Threshold (5%)')
plt.title("Isolation Forest Anomaly Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Efficiency Classification**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import IsolationForest
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import seaborn as sns

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.drop(columns=['Timestamp', 'Machine_ID'])

# Encode categorical features and labels
df['Operation_Mode'] = df['Operation_Mode'].astype('category').cat.codes
label_encoder = LabelEncoder()
df['Efficiency_Status'] = label_encoder.fit_transform(df['Efficiency_Status'])


# Feature-label split
labels = df['Efficiency_Status'].values
features = df.drop(columns=['Efficiency_Status'])

# Feature scaling
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(features_scaled, labels, test_size=0.2, random_state=42)


# Deep Learning Classification Model

print("\n Training Deep Learning Classification Model...")
model = Sequential([
    Dense(64, activation='relu', input_dim=X_train.shape[1]),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(len(np.unique(labels)), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=128,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)


# Plot Training History

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title("Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title("Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Evaluation

y_pred = np.argmax(model.predict(X_test), axis=1)
print("\n Classification Report:")
report = classification_report(y_test, y_pred, target_names=[str(cls) for cls in label_encoder.classes_])

conf = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(conf, annot=True, fmt='d',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_,
            cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

# After model training and evaluation
import shap


# SHAP: Kernel Explainer for Explainability

print("\n Running SHAP for Explainability...")

# Sample a smaller subset for SHAP to keep it fast
X_sample = shap.sample(X_test, 100)
explainer = shap.Explainer(model.predict, X_sample)
shap_values = explainer(X_sample)


# SHAP Summary Plot

shap.summary_plot(shap_values, X_sample, feature_names=features.columns)

import shap
import matplotlib.pyplot as plt

sample_index = 0

probs = model.predict(X_sample)
predicted_class = np.argmax(probs[sample_index])

# Print predicted class label
print(f"Predicted class: {label_encoder.classes_[predicted_class]} (Index: {predicted_class})")

# Create SHAP waterfall plot for this sample and predicted class
shap.plots.waterfall(shap_values[sample_index, :, predicted_class], max_display=10)

# For multi-class: average SHAP values across classes
shap_values_avg = shap.Explanation(
    values=np.mean(shap_values.values, axis=2),
    base_values=np.mean(shap_values.base_values, axis=1),
    data=shap_values.data,
    feature_names=shap_values.feature_names
)

# Plot beeswarm
shap.plots.beeswarm(shap_values_avg, max_display=10)

"""# **Predictive Maintenance Forecasting (Adaptive)**"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

# Feature scaling (only input features, not the full df including labels)
scaler = StandardScaler()
scaled = scaler.fit_transform(df.values)

# Create sequences
def create_sequences(data, seq_length=10):
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        x = data[i:(i + seq_length)]
        y = data[i + seq_length]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

seq_len = 10
X, y = create_sequences(scaled, seq_len)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

# DataLoader
train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=64, shuffle=True)
test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor), batch_size=64, shuffle=False)

# Transformer Forecasting Model (upgraded)
class TransformerForecast(nn.Module):
    def __init__(self, input_dim, model_dim=128, num_heads=8, num_layers=4):
        super().__init__()
        self.embedding = nn.Linear(input_dim, model_dim)
        encoder_layer = nn.TransformerEncoderLayer(d_model=model_dim, nhead=num_heads, dropout=0.1, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.decoder = nn.Linear(model_dim, input_dim)

    def forward(self, x):
        x = self.embedding(x)
        x = self.transformer(x)
        return self.decoder(x[:, -1])  # use last token output

# Initialize model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = TransformerForecast(input_dim=X.shape[2]).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)

# Training loop with verbose output
epochs = 100
train_losses, test_losses = [], []
for epoch in range(epochs):
    model.train()
    train_loss = 0
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    model.eval()
    test_loss = 0
    with torch.no_grad():
        for xb, yb in test_loader:
            xb, yb = xb.to(device), yb.to(device)
            test_loss += criterion(model(xb), yb).item()
    test_loss /= len(test_loader)

    train_losses.append(train_loss)
    test_losses.append(test_loss)

    print(f"Epoch {epoch+1}/{epochs} — Train Loss: {train_loss:.4f}, Test Loss: {test_loss:.4f}")

# Plot losses
plt.figure(figsize=(10, 4))
plt.plot(train_losses, label='Train Loss')
plt.plot(test_losses, label='Test Loss')
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Upgraded Transformer Forecasting Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Re-import necessary modules and reload data since kernel was reset
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

# Preprocess timestamp and sort by time
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df.sort_values(by='Timestamp', inplace=True)

# Select one machine for time-series modeling (simulate forecasting for one unit)
machine_id = df['Machine_ID'].unique()[0]
df_machine = df[df['Machine_ID'] == machine_id].reset_index(drop=True)

# Features and target for forecasting predictive maintenance score
features = ['Temperature_C', 'Vibration_Hz', 'Power_Consumption_kW',
            'Network_Latency_ms', 'Packet_Loss_%', 'Production_Speed_units_per_hr']
target = 'Predictive_Maintenance_Score'

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_machine[features])
y = df_machine[target].values

# Create sequences for LSTM (e.g., 10 timesteps)
sequence_length = 10
X_seq, y_seq = [], []
for i in range(len(X_scaled) - sequence_length):
    X_seq.append(X_scaled[i:i + sequence_length])
    y_seq.append(y[i + sequence_length])
X_seq, y_seq = np.array(X_seq), np.array(y_seq)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42)

# Define LSTM model
model = Sequential([
    LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=False),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Early stopping
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train model
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

# Evaluate model
loss, mae = model.evaluate(X_test, y_test)

# Predict and visualize
y_pred = model.predict(X_test)

# Plot predicted vs actual
plt.figure(figsize=(10, 5))
plt.plot(y_test[:100], label='True')
plt.plot(y_pred[:100], label='Predicted')
plt.title("Predictive Maintenance Forecasting")
plt.xlabel("Sample Index")
plt.ylabel("Score")
plt.legend()
plt.grid(True)
plt.show()

loss, mae

"""# **Generative Simulation Module**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Concatenate, LeakyReLU
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.utils import to_categorical

import tensorflow as tf
tf.config.run_functions_eagerly(True)


# Preprocess
#df = df.drop(columns=['Timestamp'])
df['Operation_Mode'] = LabelEncoder().fit_transform(df['Operation_Mode'])
df['Efficiency_Status'] = LabelEncoder().fit_transform(df['Efficiency_Status'])

# Sensor features
sensor_cols = ['Temperature_C', 'Vibration_Hz', 'Power_Consumption_kW',
               'Network_Latency_ms', 'Packet_Loss_%', 'Production_Speed_units_per_hr']
scaler = StandardScaler()
sensor_data = scaler.fit_transform(df[sensor_cols])

# Condition inputs: Operation_Mode + Efficiency_Status
conditions = df[['Operation_Mode', 'Efficiency_Status']].values
conditions = to_categorical(conditions[:, 0]*3 + conditions[:, 1], num_classes=9)  # 3 modes × 3 status

# GAN settings
latent_dim = 32
condition_dim = conditions.shape[1]
sensor_dim = sensor_data.shape[1]

# Generator
def build_generator():
    model = Sequential()
    model.add(Dense(64, input_dim=latent_dim + condition_dim))
    model.add(LeakyReLU(0.2))
    model.add(Dense(128))
    model.add(LeakyReLU(0.2))
    model.add(Dense(sensor_dim, activation='linear'))
    return model

# Discriminator
def build_discriminator():
    model = Sequential()
    model.add(Dense(64, input_dim=sensor_dim + condition_dim))
    model.add(LeakyReLU(0.2))
    model.add(Dense(32))
    model.add(LeakyReLU(0.2))
    model.add(Dense(1, activation='sigmoid'))
    return model

# Use separate optimizers
optimizer_d = Adam(0.0002, 0.5)
optimizer_g = Adam(0.0002, 0.5)

# Build models
generator = build_generator()
discriminator = build_discriminator()
discriminator.compile(loss='binary_crossentropy', optimizer=optimizer_d, metrics=['accuracy'])

# Combined model
z = Input(shape=(latent_dim,))
c = Input(shape=(condition_dim,))
zc = Concatenate()([z, c])
fake_sensor = generator(zc)
dc_input = Concatenate()([fake_sensor, c])
validity = discriminator(dc_input)

combined = Model([z, c], validity)
combined.compile(loss='binary_crossentropy', optimizer=optimizer_g)


# Training loop
epochs = 5000
batch_size = 64
half_batch = batch_size // 2

for epoch in range(epochs):
    idx = np.random.randint(0, sensor_data.shape[0], half_batch)
    real_sensor = sensor_data[idx]
    real_cond = conditions[idx]

    z_noise = np.random.normal(0, 1, (half_batch, latent_dim))
    gen_sensor = generator.predict(np.concatenate([z_noise, real_cond], axis=1))

    # Train discriminator
    d_loss_real = discriminator.train_on_batch(np.concatenate([real_sensor, real_cond], axis=1), np.ones((half_batch, 1)))
    d_loss_fake = discriminator.train_on_batch(np.concatenate([gen_sensor, real_cond], axis=1), np.zeros((half_batch, 1)))
    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    # Train generator
    z_noise = np.random.normal(0, 1, (batch_size, latent_dim))
    sampled_cond = conditions[np.random.randint(0, conditions.shape[0], batch_size)]
    g_loss = combined.train_on_batch([z_noise, sampled_cond], np.ones((batch_size, 1)))

    # Print progress
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | D Loss: {d_loss[0]:.4f}, Acc: {100*d_loss[1]:.2f}% | G Loss: {g_loss:.4f}")

# Generate new sensor samples
n_samples = 100
z_gen = np.random.normal(0, 1, (n_samples, latent_dim))
target_cond = np.tile(to_categorical([2*3 + 2], 9), (n_samples, 1))  # Mode=2, Efficiency=2
generated = generator.predict(np.concatenate([z_gen, target_cond], axis=1))
generated = scaler.inverse_transform(generated)

# Plot generated sensor curves
plt.figure(figsize=(10, 5))
for i in range(sensor_dim):
    plt.plot(generated[:, i], label=sensor_cols[i])
plt.title("Generated Sensor Readings (Conditioned on High Efficiency, Active Mode)")
plt.xlabel("Sample Index")
plt.ylabel("Sensor Value")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()